### ISSUE TITLE
BottomNav - Change Icons

### ISSUE THREAD

**Issue by ayushmaniac** [simformsolutions/SSCustomBottomNavigation#11]
What if someone wants to change the image itself @bottomnav, you are only changing the color.
How do one change the image of it. As well how is fragment going to get added?

**Comment by shwetachauhan-simform** [comment]
@ayushmaniac : You can add image from your main class, it's not static. I think you can find this in our demo. Let us know if you still have query.

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform this is pretty awesome, just wanted to know are we adding the fragments.

**Comment by ShwetaChauhan18** [comment]
@ayushmaniac : We will update demo very soon.

**Comment by ayushmaniac** [comment]
tried doing this way to change the icons, didn't work
 ```
var bottom = bottomNavigationView.getModelById(id)
                bottom?.apply {
                    icon = drawable
                }
```

**Comment by shwetachauhan-simform** [comment]
@ayushmaniac : https://github.com/simformsolutions/SSCustomBottomNavigation/blob/master/app/src/main/java/com/sscustombottomnavigation/MainActivity.kt

Please check this and on line no 30 you can see we added drawable icon, you can change it there.

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform that is a defined drawable for unselected items I guess, I wanted to change the icon when users clicks any menu.

**Comment by shwetachauhan-simform** [comment]
ohh, I see. That part is not implemented.

Thanks for update. We will add this.

**Comment by shwetachauhan-simform** [comment]
@ayushmaniac : We can add but it will take sometime , would be great if you can send us pr for this , I'll merge it.

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform started working on that, just wanted to know with the bumps it has a background on the back which is more than the height of the bump, how to remove it?

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform can you explain me the above mentioned

**Comment by shwetachauhan-simform** [comment]
Can you please add screen shot for that? I will check it and update you by tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform already added screenshot, check the above mentioned point.

**Comment by ayushmaniac** [comment]
@shwetachauhan-simform any luck?
